#!/bin/bash
#!/bin/bash
test() {
  echo "------------------------------"
  echo "app: $1"
  emend --verbose --app $1 
}

test amber
test atom
test autodoc
test bash-git-prompt
test brew
test brew-update
test colors
test cxxtest
test default-jdk
test default-jre
test docbld
test dotfiles
test eclipse-platform
test emend
test emend-computer
test fzf
test gcc
test google-chrome
test gradle
test haskell
test iterm2
test keycastr
test latexmk
test maven
test miktex
test mutt
test openconnect
test openjdk-8-jdk
test openjre-8-jre
test operating-system
test perl
test sdkman
test selenium
test ssh
test symlink
test texlive
test texstudio
test tlc-article
test tmux
test vim
test vscode
test xcode
