# {{{ Repositories
repos:
  - repo:
    url: http://github.com
    paths:
      - source: Traap/ui-automation
        target: ~/git/ui-automation

# -------------------------------------------------------------------------- }}}
